### ISSUE TITLE
Consider spliting Value::Int into 32 and 64 bit variants?

### ISSUE THREAD

**Issue by tyt2y3** [blackbeam/rust_mysql_common#24]
https://github.com/blackbeam/rust_mysql_common/pull/17/files
I see that there is a recent change in splitting floating point values into 32 and 64 bit variants.
Would you also agree splitting integers, where 32 bit is called Int, and 64 bit is BigInt ? This aligns more with MySQL numeric types names.
It definitely breaks current behavior, but I consider that more appropriate in the long run.

On the other hand, I spotted that, https://github.com/blackbeam/rust_mysql_common/blob/master/src/value/mod.rs#L256
shouldn't we convert unsigned types to UInt instead?

If you'd agree, I can create a PR on this.

**Comment by blackbeam** [comment]
Hi. The motivation behind #17 is to avoid implicit precision loss.
As far as I can see there is no data loss in integer types, so I don't think we should split it.

> On the other hand, I spotted that, https://github.com/blackbeam/rust_mysql_common/blob/master/src/value/mod.rs#L256
shouldn't we convert unsigned types to UInt instead?

The rule of thumb here is to use i64 for everything except unsinged `MYSQL_TYPE_LONGLONG` because there is no need to save information about the in-wire type (this information has no value). The truth is that in-wire type does not need to exactly match schema and vice-versa.

**Comment by tyt2y3** [comment]
Thank you for your reply. You are right about that in-wire type does not necessary match the schema.
